
version: '3'
services:
  bokehapp:
    build:
      context: .
      dockerfile: bokehapp.Dockerfile
    ports:
      - '5006:5006'
    volumes:
      - './:/app'
    image: qmxp55/bokehapp:1.1
  flaskapp:
    depends_on:
      - bokehapp
    build:
      context: .
      dockerfile: flaskapp.Dockerfile
    volumes:
      - './:/app'
    command: gunicorn --bind 0.0.0.0:5000 main:app
    ports:
      - '5000:5000'
    image: qmxp55/flaskapp:1.1
