apiVersion: v1
kind: ReplicationController
metadata:
  name: lsvi-rc
spec:
  replicas: 3
  selector:
    name: lsvi
    version: v1
  template:
    metadata:
      labels:
        name: lsvi
        version: v1
    spec:
      containers:
        - name: flaskapp
          command: ["gunicorn", "--bind", "0.0.0.0:5000" ,"main:app"]
          image: gcr.io/lsvi-cutout-290921/flaskapp:v6
          ports:
            - containerPort: 5000
        - name: bokehapp
          #command: ["bokeh", "serve", "--port", "5006", "--allow-websocket-origin=34.122.27.211", "script.py"]
          command: [ "bokeh", "serve", "script.py" ]
          image: gcr.io/lsvi-cutout-290921/bokehapp:v3
          ports:
            - containerPort: 5006
#      initContainers:
#        - name: init-bokehapp
#          image: gcr.io/lsvi-cutout-290921/bokehapp:v1
#          command: ['sh', '-c', "sleep 2"]
#          ports:
#            - containerPort: 5006
